### PR TITLE
added ignore errors check inside runCommand to address promise except…

### PR DESCRIPTION
**Pull request by rommik**
I am not sure if this is the best way to solve the problem. This is how I fixed it for my case.

The issue is that exception is thrown after the main for loop is finished, and gulp's pipeline is interrupted.

### CODE REVIEW

**Comment by Klathmon** [comment]
Thanks for this, I'm surprised someone found and is using this!

I'd love to merge this in, but I can't with the package.json and readme changes to another name.

Would you be interested as taking over the project as the main contributor? I can give you full access to the repo as it seems you are using it more than I am!

**Comment by rommik** [comment]
@Klathmon oh I'm surprised, I find your work very useful for those who need to run gulp on windows & linux. I apologize for the messed up PR, I did the readme and package change for my temporary repository, and committed it into the same branch. My mistake.  I can over as the main contributor, but except this one bug, otherwise the module is great :)

**Comment by Klathmon** [comment]
@rommik  just pinging you again here, if you can remove those package.json and readme changes I can merge this in.

And if you are serious about maybe being a maintainer, email me at gregbenner1@gmail.com and I can set you up with write permissions on the repo, and publish permissions for NPM.

**Comment by jramoyo-siteminder** [comment]
@rommik @Klathmon was trying to fix this issue on an older version... rather than pass the `ignoreErrors` flag everywhere, it might be better to `reject` the Promise rather than throw an exception -- that way, the exception is caught by the catch block in `run()`

**Pull request closed without merging**
